#!/bin/sh

branch=`git symbolic-ref --short -q HEAD`
showedProject[0]=0
projectArray[0]="testBundle"

function fetchProject()
{
	index=0
	for file in `ls | grep "^O2O"`
	do
		if [ -d $file  &&  "$file" != "O2O" ] 
		then
			echo "$file"
			showedProject[$index]=0
			projectArray[$index]="$file"
			let index++
		fi
	done
	
}

function showAlertMessage()
{	
	project="$1"
	if cat git_commit_data.txt | grep "/${project}/" > /dev/null
	then
		if [ ${showedProject[$2]} -eq 0 ] 
		then
			showedProject[$2]=1
			echo "⚠️  ⚠️  ⚠️  You should deploy $project after push, don't forget it! ⚠️  ⚠️  ⚠️"
		fi
	fi
}

function main()
{
	#获取项目名称
	fetchProject

	#获取commit id
	git log $branch ^origin/$branch | grep 'commit' | sed 's/^commit//g' > git_log_data.txt

	if [ -s "git_log_data.txt" ] 
	then
		cat git_log_data.txt | while read line 
		do
			if [ -n "$line" ]
			then
				git show $line > git_commit_data.txt
				if [ -s "git_commit_data.txt" ]
				then
					index=0
					for projectName in ${projectArray[*]}
					do
						#判断是否已经展示
						showAlertMessage $projectName $index
						let index++
					done	
					: > git_commit_data.txt
				fi		
			fi
		done
	else
		echo "🌲  🌲  🌲  Let it go"
	fi

	rm -rf git_log_data.txt
	rm -rf git_commit_data.txt
}

main
exit 0
